export enum JobAction {
  GENERATE_RESUME = "GENERATE_RESUME",
  GENERATE_COVER_LETTER = "GENERATE_COVER_LETTER",
  FIND_EMPLOYEES = "FIND_EMPLOYEES",
  GENERATE_REFERRAL = "GENERATE_REFERRAL",
  APPLY = "APPLY",
  FOLLOW_UP = "FOLLOW_UP",
  SKIP = "SKIP"
}