export enum JobStatus {
  DISCOVERED = "DISCOVERED",
  ANALYZED = "ANALYZED",
  RESUME_GENERATED = "RESUME_GENERATED",
  EMPLOYEES_FOUND = "EMPLOYEES_FOUND",
  REFERRAL_READY = "REFERRAL_READY",
  REFERRAL_SENT = "REFERRAL_SENT",
  APPLIED = "APPLIED",
  REJECTED = "REJECTED",
  INTERVIEW = "INTERVIEW",
  OFFER = "OFFER",
  HIRED = "HIRED",
  SKIPPED = "SKIPPED"
}